name: "Demo workflow"

permissions:
  contents: write 

on: push

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      # 1. This step downloads your repository files onto the runner
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full commit history so you don't get history errors

      # 2. Your custom steps go below here
      - name: "Print Hello world"
        run: echo "Hello world"
